### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by bntti** [Ejo0/verkkokauppasovellus#1]
# Vertaisarviointi

### /register
- Jos rekisteröityessä tulee virhe niin käyttäjänimikenttä tyhjentyy
- Epäselviä virheilmoituksia
  - Eriävät salasanat: `Virhe: Tarkista salasana`
  - Käyttäjätunnus jo käytössä: `Virhe: Käyttäjätunnus ei kelpaa`
- Salasana ja käyttäjänimi voivat olla tyhjiä

### /login
- Jos kirjautuessa tulee virhe, nin käyttäjänimi tyhjentyy
- Kirjautumissivulla ei ole `Palaa etusivulle` nappia

### /product/{id}
- Jos id ei ole olemassa, niin seuraa `Internal Server Error`
  - Esimerkiksi https://verkkokauppasovellus.herokuapp.com/product/123

### /admin/product/{id}
- `Näytä tuote valikoimassa` checkbox on aina päällä riippumatta siitä, että näytetäänkö tuote valikoimassa vai ei

### /admin
- Jos tuotetta luodessa tulee virhe, nin kentät tyhjentyvät
- Jos yrittää lisätä tuotteen jolla ei ole hintaa, niin seuraa `Internal Server Error`
- Virhe `Tarkista syöte!` ei ole kuvaava
- Tuotteella voi olla negatiivinen hinta
- Tuotteen nimen ja kuvauksen pituuksilla ei taida olla maksimirajoja (muillakaan kentillä nettisivulla ei taida olla)

### Muuta
- Kun menee `https://verkkokauppasovellus.herokuapp.com/admin` ja ei ole admin, niin tulee hyvin uudelleenohjaus login-sivulle ja kuvaava virheviesti

## Koodi
- Useita tyylivirheitä. (Kurssin [Tekninen tarkastuslista](https://hy-tsoha.github.io/materiaali/tekninen_tarkastuslista/))
  - Suosittelen käyttämään jonkinlaista koodin automaattista formatoijaa
    - Visual Studio Coden saa automaattisesti formatoimaan aina tallentaessa
- Kuka tahansa taitaa pystyä poistamaan tavaroita toisten ostoskoreista
- Muuten koodi tyylikästä ja siistiä

### Ehdotus
`/routes.py` rivit 151 - 157
```py3
new_name = request.form["name"]
if not new_name: new_name = product.name
# Voisi olla
new_name = request.form["name"] if request.form["name"] else product.name
# Jne.
```

## Tietokanta
- Users tablessa `role TEXT` sijasta voisi olla `admin BOOLEAN`
- Products tablessa `active` sanan voisi korvata sanalla `hidden`

### Tietokantakyselyt koodissa
`/services/cart.py` rivi 5
```py3
sql = "SELECT id, quantity FROM cart_items WHERE user_id =:user_id AND product_id=:product_id"
# Pitäisi joko olla
sql = "SELECT id, quantity FROM cart_items WHERE user_id = :user_id AND product_id = :product_id"
# tai
sql = "SELECT id, quantity FROM cart_items WHERE user_id=:user_id AND product_id=:product_id"
```

Useamman rivin SQL-komennot olisivat siistimpiä koodissa jos ne alkaisivat samalta riviltä
```py3
# Korvaa tämä
sql = """INSERT INTO cart_items (user_id, product_id, quantity, created_at)
        VALUES (:user_id, :product_id, :quantity, NOW())"""
# Tällä
sql = """INSERT INTO cart_items (user_id, product_id, quantity, created_at)
         VALUES (:user_id, :product_id, :quantity, NOW())"""
```

`Select *` ei pitäisi käyttää
`/services/orders.py` rivi 7
```py3
# 'SELECT *' Ei pitäisi käyttää
sql = "SELECT * FROM order_details"
```

SQL-komennon voisi siistiä
`/services/cart.py` rivit 24 - 30
```sql
SELECT COALESCE(SUM(products.total), 0)
FROM (
    SELECT p.price * c.quantity AS total
    FROM products p, cart_items c
    WHERE p.id = c.product_id
    AND c.user_id = :user_id
) AS products

-- Voisi olla
SELECT COALESCE(SUM(p.price * c.quantity), 0)
FROM products p, cart_items c
WHERE p.id = c.product_id AND c.user_id = :user_id
```

## HTML
- `/templates/login.html` ja `/templates/register.html` eivät käytä layouttia

`admin/index.html` rivi 24
```html
{% for product in products%}
<!-- Pitäisi olla -->
{% for product in products %}
```

**Comment by ejokela** [comment]
Hyviä huomioita ja vinkkejä, näitä hyödynnetty!
