### ISSUE TITLE
Vertaisarvointi 2

### ISSUE THREAD

**Issue by piamanns** [Ejo0/verkkokauppasovellus#2]
Kaikki toiminnot toimivat Herokussa odotetulla tavalla. 
Mieleeni tuli muutamia lisätoiminnallisuuksia, jotka voisivat vielä parantaa käyttökokemusta:

### Asiakas:
- Kun tuotteen lisää ostoskoriin, ainoa palaute käyttäjälle tapahtuman onnistumisesta on se, että ostoskorin summa nousee, mikä helposti jää huomaamatta. Lisää ostoskoriin-napin painallus voisi viedä käyttäjän takaisin tuotelistaukseen. Vahvistusviesti (“Tuote x lisättiin ostoskoriin”) olisi mukava lisä.
- Koko ostoskorin kerralla tyhjentävä nappi olisi kätevä.

### Admin:

- Ylläpitäjälle voisi lisätä mahdollisuuden poistaa/piilottaa arvioita.
- Tuotteen tietoja päivittäessä olisi mukavaa, jos tuotteen nykyiset tiedot olisi tuotu valmiiksi päivityslomakkeeseen. Tämä helpottaisi esimerkiksi kirjoitusvirheen korjaamista.
- Tuotetietojen päivityksen yhteydessä kaipaan Vahvista muutokset-painalluksen jälkeen selkeämpää vahvistusta sille, että jotain todellakin tapahtui. Jos esimerkiksi tuotteen poistaa valikoimasta, tuotesivu latautuu uudestaan, jolloin päivityslomakkeen Näytä tuote valikoimassa on jälleen valittuna. (Tämäkin hämmennys poistuisi, jos päivityslomakkeen sisältö heijastaisi tuotteen nykyistä tilaa.) Vahvista muutokset-napin painallus voisi viedä ylläpitäjän takaisin tuotelistaukseen.
- Toimitettujen tilausten listauksessa voisi id-numeron sijaan olla käsittelijän nimi.
- Onko jotain tiettyä syytä sille, että Admin-tunnuksella ei voi tehdä ostoksia?

Sovelluksen ulkoasu on hieman karu. Ehkä aikaa löytyisi vielä tämän asian parantelemiseen? 
Tuotteilla voisi myös olla kuva.

Tekninen toteutus on hyvä. 
Pienenä yksityiskohtana voisi mainita routes.py:n add_review-funktion, joka poikkeuksen tapahtuessa voisi antaa jonkinlaisen palautteen siitä, mitä meni pieleen:

```python
try:
    grade = int(request.form["grade"])
        if grade in [1,2,3,4,5] and len(content) in range(1,501) and products.is_active(product_id):
            reviews.add_review(product_id, grade, content)
except:
    pass
return redirect(f"/product/{product_id}")
```

**Comment by ejokela** [comment]
Hyviä huomioita! Priorisointisyistä aikaa oli näille niukasti, harmillisesti.
